name: Release

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  release:
    name: Create a new release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm trusted publishing

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_TOKEN }}
      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10
      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          cache: "pnpm"
      - run: pnpm install

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: 0
        run: npx semantic-release
